"""Backward-compatibility shim.

All database logic has moved to the ``db`` package.
This module re-exports everything so that any code that still does
``import database as db`` or ``from database import X`` continues to work.
"""

from db import *          # noqa: F401, F403
from db import (          # noqa: F401  (explicit re-export for type-checkers)
    DB_PATH,
    YEARS,
    PROTECTED_STATUSES,
    DEFAULT_STATUSES,
    PENDING_STATUSES,
    get_connection,
    get_dynamic_years,
    init_db,
    clear_demo_data,
    get_status_options,
    add_status,
    delete_status,
    get_setting,
    set_setting,
    get_all_settings,
    get_users,
    count_users,
    add_user,
    delete_user,
    get_user_by_username,
    get_pending_for_reminders,
    create_reminder,
    get_reminders,
    dismiss_reminder,
    dismiss_all_reminders,
    get_unread_reminder_count,
    get_stats,
    get_status_counts,
    get_apps_per_year,
    get_success_rate_per_year,
    get_company_note_frequency,
    get_companies,
    get_company,
    add_company,
    update_company,
    delete_company,
    bulk_delete_companies,
    get_applications,
    search_applications,
    get_application,
    get_application_timeline,
    add_application,
    update_application,
    delete_application,
    bulk_delete_applications,
    bulk_update_applications,
    find_duplicate_applications,
    bulk_import_applications,
    save_ai_fit,
)
